name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        # Updated to v4
        uses: actions/checkout@v4

      - name: Setup Node
        # Updated to v4
        uses: actions/setup-node@v4
        with:
          node-version: '20' # It's good practice to specify a Node.js version

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Build project
        run: npm run build

      - name: Upload production-ready build files
        # Updated to v4
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: ./dist
          # Add this line to ensure compatibility with v4's default behavior
          retention-days: 1 

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download artifact
        # Updated to v4
        uses: actions/download-artifact@v4
        with:
          name: production-files
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
